name: Build and Deploy to Host

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Refactor Assets
        run: |
          sed -i "s/charts.phicommunity.com.cn/charts-phicommunity.xmdisk.ga/g" `grep charts.phicommunity.com.cn -rl ./`
          rm -rf ./assets/images/Avatar.svg
          wget https://drv.lolimstatic.ml/drive2/PhiCommunity/Avatar.svg
          mv ./Avatar.svg  ./assets/images/
          
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17'

      - name: Setup Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Setup Webpack & Install Dependences
        run: |
          npm install webpack-cli webpack -g
          npm install
          
      - name: Build
        run: |
          npm run build
          
      - name: Upload Artchive
        uses: actions/upload-artifact@v3.0.0
        with:
            name: PhiCommunity-Nodejs-Artfact
            path: dist
  
      - name: Static gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
